### PR TITLE
Adjust quick install guide since we are making a repository on the fly

### PR DESCRIPTION
**Pull request by igorpecovnik**
After verifying if we put it into wanted folders and if it works, automation builds upon changes.

### CODE REVIEW

**Review by Tearran — APPROVED** [review]

**Review by Tearran — COMMENTED** [review]
https://github.com/armbian/configng/blob/main/lib/armbian-configng/documents.sh#L206

Will Overwrite changes here

**Comment by igorpecovnik** [comment]
So we want to have README generated via Github actions?

**Comment by Tearran** [comment]
Automating the documentation is part or the project, since brand name issues or and compatibility remain concern within the community. Seemed prudent to use brand as naming convention. $filename --dev uses lib/$filename/* 

Where to direct it was unclear, so an option or Placeholder was made.  #20 cleared so A test to Redirecting to share/doc/$filename/  [documents](https://github.com/armbian/configng/blob/main/lib/armbian-configng/documents.sh#L206)  works locally Can delete the whole folder and armbian-confign will make folder share/doc/armbian-config 

## Naming conventions
### For example
`ln -s armbian-configng armbian-configng-dev`  will try and use `lib/armbian-configng-dev/*`  if it exist. 
` cp -r  lib/armbian-configng lib/armbian-configng-dev`  
currently wil output branded documents to banded doc folder.

### Alternatively
`unsupported-config` would look for `lib/Unsupported-config`

**Comment by Tearran** [comment]
@igorpecovnik 

> So we want to have README generated via Github actions?

Not really, Was originally intended to have separate readme per `Category`.  In a doc folder.  This was the compromised that was made when it was agreed to direct focus away from [building and understanding ](https://github.com/Tearran/configng/tree/testing-deb_packages) how a *.deb are built. 

The doc generators can be easily directed to the share/doc folder now.

**Comment by igorpecovnik** [comment]
ok. merging this?

**Comment by Tearran** [comment]
Yes. Ran fine on a codespace. 

Not sure, about the ci/cd. I only spent few days to get familiar with what a ci/cd pipeline is.

**Comment by igorpecovnik** [comment]
> Not sure, about the ci/cd. I only spent few days to get familiar with what a ci/cd pipeline is.

CI complains about the SheelCheck inconsistency and that has to be taken into account. For future. I also need to add to skip non bash files.

**Pull request merged**
