### PR TITLE
Fix multiple typo's

### PR DESCRIPTION
**Pull request by schwar3kat**
Fixing typo's in multiple files.

### CODE REVIEW

**Comment by Tearran** [comment]
It appears that the README.md file might have been manually edited. For consistency and to ensure that documentation updates are accurately reflected, please use the armbian-configng --doc command. This command updates README.md without requiring sudo and ensures that all changes are properly included.

Additionally, considering the importance of maintaining accurate and up-to-date documentation, it might be beneficial to implement a questionnaire for pull requests similar to the one used by Armbian Build. This would help ensure that all necessary steps are followed and documentation is updated appropriately.

a proposed template for such a questionnaire has beene added to the

**Comment by schwar3kat** [comment]
Where are the instructions to do this  :(

**Comment by schwar3kat** [comment]
> It appears that the README.md file might have been manually edited. For consistency and to ensure that documentation updates are accurately reflected, please use the armbian-configng --doc command. This command updates README.md without requiring sudo and ensures that all changes are properly included.
Where are the instructions to do this?...
Twice now I have wasted my time trying to correct your errors using standard git methodology.

**Comment by Tearran** [comment]
> 
> Where are the instructions to do this?...
> 

Thanks for pointing this out! Separating the development and user instructions has been a bit tricky. The README is usually for devs, but it seems like the docs are leaning towards users. Do you have any suggestions on how we can split these up better?

> 
> I dropped the README.md commit on a local clone, then ran armbian-configng --doc. I compared the results, and there still a typo.
> 

I'm a bit confused here. Did you manage to fix said typo, or is it still there? Please let me know so I can address it appropriately.

> 
> I also discovered that a script from config.ng.docs.sh was expanding variables when writing to README.md and hard coding the architecture of the machine where armbian-configng --doc was run.
> 

 I see you’ve caught the missing escape slash already and corrected this. Thanks for catching that and fixing it!

**Comment by schwar3kat** [comment]
All typo's that I spotted are fixed.

**Pull request merged**
