### PR TITLE
Refactoring network configuration

### PR DESCRIPTION
**Pull request by igorpecovnik**
# Description

As we recently switched one level higher to defining network configuration via Netplan, all existing routines become deprecated. This commit adds initial support for handling wired and wireless networking. 

Problems - doesn't list sub routines:
`sudo bin/armbian-configng --cli N01`

jq: error (at bin/../lib/armbian-configng/config.ng.jobs.json:584): Cannot iterate over null (null)

Question:

What is simplest way to:

- pick and pass parameters further - IP, password
- collect users input via GUI  (reading IP, password, ...)

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have ensured that my changes do not introduce new warnings or errors
- [ ] No new external dependencies are included
- [ ] Changes have been tested and verified
- [ ] I have included necessary metadata in the code, including associative arrays

### CODE REVIEW

**Comment by Tearran** [comment]
--cli jq Cannot iterate over null (null) error was fixed and merged

https://github.com/armbian/configng/pull/49/files#diff-dbcb1397135f88ba1f1e2aed3147cb4d6ebd06f37de447699532c19254674d1c

 test done `sudo bin/armbian-configng --cli N01`  ran debconfig UX as expected 


 use of the --api flag option such as would be the esist and most direct way. 
 
 in this case the "UI/UX" command need to be move the helpers. 
to be ran 
`sudo sudo bin/armbian-configng --api remove_bluetooth` or `sudo bin/armbian-configng --api 
 insatll_bluetooth`
 an example helper function and metadata like so. 

```
module_options+=(
["remove_bluetooth,author"]="Igor Pecovnik"
["remove_bluetooth,ref_link"]=""
["remove_bluetooth,feature"]="remove_bluetooth"
["remove_bluetooth,desc"]="Remove bluetooth support"
["remove_bluetooth,example"]="remove_bluetooth"
["remove_bluetooth,status"]="Active"
)
#
# @description Remove bluetooth support
#
remove_bluetooth () {
	see_current_apt 
	debconf-apt-progress -- apt-get -y remove bluetooth bluez bluez-tools
	check_if_installed xserver-xorg && debconf-apt-progress -- apt-get -y remove pulseaudio-module-bluetooth blueman
	debconf-apt-progress -- apt -y -qq autoremove
}

module_options+=(
["install_bluetooth,author"]="Igor Pecovnik"
["install_bluetooth,ref_link"]=""
["install_bluetooth,feature"]="install_bluetooth"
["install_bluetooth,desc"]="Install bluetooth support"
["install_bluetooth,example"]="install_bluetooth"
["install_bluetooth,status"]="Active"
)
#
# @description Install bluetooth support
#
insatll_bluetooth () {
	see_current_apt 
	debconf-apt-progress -- apt-get -y install bluetooth bluez bluez-tools
	check_if_installed xserver-xorg && debconf-apt-progress -- apt-get -y install pulseaudio-module-bluetooth blueman
}
```

reasoning: separated the ui/ux development responsibility from system critical development

**Comment by Tearran** [comment]
I am confused GUI is taken care of in most desktops with networkmanager . text user interface nmtu man page shows

**Comment by igorpecovnik** [comment]
> test done sudo bin/armbian-configng --cli N01 ran debconfig UX as expected

Doesn't work for me.

**Comment by igorpecovnik** [comment]
> The issue for me is that the JSON is for UI/UX commands, not features.

So JSON strictly for calling functions containing nothing else?

**Comment by Tearran** [comment]
There is flexibility with the json. But a priority for features should be in function. Simpler to make a function that is available to the command line. then to sort and parse through the nesting of a menu.

**Comment by igorpecovnik** [comment]
@Tearran did many tests, but still it might break ... Functional wise I won't proceed further for v1.0

**Pull request merged**
