### PR TITLE
Add support for desktop install

### PR DESCRIPTION
**Pull request by igorpecovnik**
Needs https://github.com/armbian/configng/pull/3

### CODE REVIEW

**Comment by Tearran** [comment]
There is a growing movement to rethink accessibility as customization. This approach recognizes that accessibility features, such as dark mode, live caption, and text-to-speech functionality, can benefit everyone, not just users with disabilities. [By reframing accessibility as customization, technology designers can create products that are more inclusive and user-friendly for all users

 In short anything done different then the base system for a server is to make accessable for a end-user. And similar functions should be kept together. Embrace it.  
(https://blog.google/outreach-initiatives/accessibility/world-sight-day-accessibility-customization/).

**Comment by Tearran** [comment]
related to #9  
Approach:

 ` apt-cache search armbian desktop `
```
armbian-bookworm-desktop-budgie - Armbian desktop for Debian bookworm
armbian-bookworm-desktop-cinnamon - Armbian desktop for Debian bookworm cinnamon
armbian-bookworm-desktop-gnome - Armbian desktop for Debian bookworm
armbian-bookworm-desktop-kde-plasma - Armbian desktop for Debian bookworm
armbian-bookworm-desktop-mate - Armbian desktop for Debian bookworm
armbian-bookworm-desktop-xfce - Armbian desktop for Debian bookworm xfce
armbian-bookworm-desktop-xmonad - Armbian desktop for Debian bookworm
```

 # search apt for armbian desktop 
 ` apt-cache search armbian desktop | awk -F " - " '{print $1, $2}' | tui -m | tui -o ` ; return 0

[wiki example ](https://github.com/Tearran/configng/wiki/tui#menu-selection-box)

**Comment by Tearran** [comment]
metapackage Is commonly use in above type of packages descriptions. 

If ad ( metapackage ) to end of apt  description for armbian desktop and any armbian specific package should offer  a Package installer or sorts Ie softly. 

Using this current name conventions 
` apt-cache search armbian desktop  metapackage | awk -F " - " '{print $1, $2}' `  
should output as above 

` apt -cash search armbian "category" metapackage | awk -F " - " '{print $1, $2}' ` 
should result is a compatibly with above

**Comment by igorpecovnik** [comment]
> This approach recognizes that accessibility features, such as dark mode, live caption, and text-to-speech functionality, can benefit everyone, not just users with disabilities.

I think that accessibility should be present by default if possible. Even with no disabilities per se we are all affected at least by ageing which brings all sorts of limitations. In my case - I keep getting bigger and bigger screen, while resolution stays the same ;)

Keep the good work!

**Pull request closed without merging**
