### PR TITLE
dynamic document (software) FInal draft

### PR DESCRIPTION
**Pull request by Tearran**
Sub category need to have disabled when its parent is disabled, with this draft.

### CODE REVIEW

**Comment by Tearran** [comment]
The idea here 
- Use Unique names for menus, Unique id's for the sub items. Another example S07.1 could be renamed SSH. 
- use jq to parse the JSON is much faster then using bash arrays. 
- Shows use of prompt in document, alternatively a perhaps an "about": "About the software" added to json, for the doc gen
- Show use of "src_link"

**Comment by Tearran** [comment]
2nd draft used `python3` and its included json module 

Intended use is for github actions. the folder is here to show the files output.  can be removed if py script is accepted. 

to generate multiple markdown files. Two files for each category. A user md and technical md
```
./tools/config-dynamic-docs.py
```
output
```
./docs/*.md
```

**Comment by igorpecovnik** [comment]
This is better approach and i think enough for start.

**Comment by igorpecovnik** [comment]
Few ideas:
- possibility to have software titles in separate files: desktops.md, netconfig.md, containers.md
- set anchor on title instead of command_id
- introduce new field title and keep description for longer text, for description what this is about. Currently we would copy all descriptions to title and adjust it afterwards.

**Comment by Tearran** [comment]
> possibility to have software titles in separate files: desktops.md, netconfig.md, containers.md

New script  folders for each Category and markdown for its sub 

> set anchor on title instead of command_id

- used Title instead of id for readable link
- used html to hide the anchor

**Comment by Tearran** [comment]
>introduce new field title and keep description for longer text, for description what this is about. Currently we would copy all descriptions to title and adjust it afterwards.

This is a more a naming issue then the need for new fields. 

The prompt, along with offering a cancel option, was originally intended to provide longer text for the commented "... what its about" field in the markdown.

Renaming "Description" to "Title" and "Prompt" to "About" should achieve the desired outcome.

**Comment by Tearran** [comment]
### tests 
from "prompt" to "about"

- [x] `./bin/armbian-config --help`
- [x] `./bin/armbian-config --help cmd`
- [x] `./bin/armbian-config --cmd M03
- [x] `./bin/armbian-config` Run N16 from menu
- [x] `./tools/config-markdown.py`

all operate as expected

**Comment by Tearran** [comment]
https://github.com/armbian/configng/blob/02357596b9aad88a15c4e537e1e2bad6d08c6eed/docs/

**Comment by Tearran** [comment]
With focus on User docs. Added options `-u |  --user` and `-t | --technical` for seperation

**Review by igorpecovnik — DISMISSED** [review]
> With focus on User docs. Added options to config-markdown

Looks perfect. I wouldn't go deeper here. We might change styling, but that is trivial and we don't need to bother with it now. I suggest to merge this if prompt/about changes are also done.

**Comment by igorpecovnik** [comment]
I have added to the main documentation:
https://github.com/armbian/documentation/pull/498
+ enabling auto pull once those both PRs are merged.

Note:
https://raw.githubusercontent.com/armbian/documentation/refs/heads/import-ac/docs/User-Guide_Armbian-Config/System/System.user.md

TOC is not needed as its auto made from markdown headings.

**Comment by Tearran** [comment]
> TOC is not needed as its auto made from markdown headings:

To better resemble the Noted, commented out `#`  generate_anchor_links (TOC) from user generation `config-markdown -u`

**Comment by igorpecovnik** [comment]
Merged, looks nice: https://docs.armbian.com/User-Guide_Armbian-Config/

**Pull request merged**
